############################################################################################################# server
server:
  port: 9000
############################################################################################################# spring
############################################################################################################# eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka1.com:8761/eureka,http://eureka2.com:8762/eureka
spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: