############################################################################################################# spring
spring:
  application:
    name: _02_config_center_v1 #与项目名保持一致
  profiles:
    active: dev