############################################################################################################# spring
spring:
  application:
    name: _03_server_provide_v2
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
############################################################################################################# actuator
management:
  endpoints:
    jmx:
      exposure:
        include: "*" #有坑，不写引号不好使
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
############################################################################################################# custom
custom:
  demoConfigParam: "custom param v1"